### ISSUE TITLE
Loaders de imagenes

### ISSUE THREAD

**Issue by DiegoDelgadoMao** [DiegoDelgadoMao/testing-webpack-plus-react#3]
para que soporte la carga de imagenes mediante las importaciones

**Comment by DiegoDelgadoMao** [comment]
- [x] con sus respectivos hash en el archivo de configuración para producción 
- [x] sin hashes para el archivo de configuración de modo de desarrollo de webpack

**Comment by D0nlist4r** [comment]
Intentare hacerlo aun que no recuerdo bien como era xd pero ya me pongo en eso

**Comment by D0nlist4r** [comment]
Bro mejor se lo dejo a usted por alguna razon ahora tambien tengo problemas para generar el archivo en dist
